INSERT INTO nivel(id, descripcion) VALUES
    (1, 'INICIAL'),
    (2, 'PREPARATORIA'),
    (3, 'EDUCACIÓN GENERAL BÁSICA ELEMENTAL'),
    (4, 'EDUCACIÓN GENERAL BÁSICA MEDIA'),
    (5, 'EDUCACIÓN GENERAL BÁSICA SUPERIOR'),
    (6, 'BACHILLERATO EN CIENCIAS');