INSERT INTO pais (codigo_numerico, codigo_alpha2, codigo_alpha3, nombre_comun, nacionalidad) VALUES
                 (4, 'AF', 'AFG', 'Afganistán', 'Afgano'),
                 (8, 'AL', 'ALB', 'Albania', 'Albanés'),
                 (12, 'DZ', 'DZA', 'Argelia', 'Argelino'),
                 (20, 'AD', 'AND', 'Andorra', 'Andorrano'),
                 (24, 'AO', 'AGO', 'Angola', 'Angoleño'),
                 (28, 'AG', 'ATG', 'Antigua y Barbuda', 'Antiguano'),
                 (32, 'AR', 'ARG', 'Argentina', 'Argentino'),
                 (36, 'AU', 'AUS', 'Australia', 'Australiano'),
                 (40, 'AT', 'AUT', 'Austria', 'Austriaco'),
                 (44, 'BS', 'BHS', 'Bahamas', 'Bahameño'),
                 (48, 'BH', 'BHR', 'Baréin', 'Bareiní'),
                 (50, 'BD', 'BGD', 'Bangladés', 'Bangladesí'),
                 (51, 'AM', 'ARM', 'Armenia', 'Armenio'),
                 (52, 'BB', 'BRB', 'Barbados', 'Barbadense'),
                 (56, 'BE', 'BEL', 'Bélgica', 'Belga'),
                 (60, 'BM', 'BMU', 'Bermudas', 'Bermudeño'),
                 (64, 'BT', 'BTN', 'Bután', 'Butanés'),
                 (68, 'BO', 'BOL', 'Bolivia', 'Boliviano'),
                 (70, 'BA', 'BIH', 'Bosnia y Herzegovina', 'Bosnio'),
                 (72, 'BW', 'BWA', 'Botsuana', 'Botsuano'),
                 (76, 'BR', 'BRA', 'Brasil', 'Brasileño'),
                 (84, 'BZ', 'BLZ', 'Belice', 'Beliceño'),
                 (96, 'BN', 'BRN', 'Brunéi', 'Bruneano'),
                 (100, 'BG', 'BGR', 'Bulgaria', 'Búlgaro'),
                 (104, 'MM', 'MMR', 'Myanmar', 'Birmano'),
                 (108, 'BI', 'BDI', 'Burundi', 'Burundés'),
                 (112, 'BY', 'BLR', 'Belarús', 'Bielorruso'),
                 (116, 'KH', 'KHM', 'Camboya', 'Camboyano'),
                 (120, 'CM', 'CMR', 'Camerún', 'Camerunés'),
                 (124, 'CA', 'CAN', 'Canadá', 'Canadiense'),
                 (140, 'CF', 'CAF', 'República Centroafricana', 'Centroafricano'),
                 (152, 'CL', 'CHL', 'Chile', 'Chileno'),
                 (156, 'CN', 'CHN', 'China', 'Chino'),
                 (170, 'CO', 'COL', 'Colombia', 'Colombiano'),
                 (188, 'CR', 'CRI', 'Costa Rica', 'Costarricense'),
                 (191, 'HR', 'HRV', 'Croacia', 'Croata'),
                 (192, 'CU', 'CUB', 'Cuba', 'Cubano'),
                 (196, 'CY', 'CYP', 'Chipre', 'Chipriota'),
                 (203, 'CZ', 'CZE', 'República Checa', 'Checo'),
                 (208, 'DK', 'DNK', 'Dinamarca', 'Danés'),
                 (214, 'DO', 'DOM', 'República Dominicana', 'Dominicano'),
                 (218, 'EC', 'ECU', 'Ecuador', 'Ecuatoriano'),
                 (222, 'SV', 'SLV', 'El Salvador', 'Salvadoreño'),
                 (226, 'GQ', 'GNQ', 'Guinea Ecuatorial', 'Ecuatoguineano'),
                 (231, 'ET', 'ETH', 'Etiopía', 'Etíope'),
                 (232, 'ER', 'ERI', 'Eritrea', 'Eritreo'),
                 (233, 'EE', 'EST', 'Estonia', 'Estonio'),
                 (246, 'FI', 'FIN', 'Finlandia', 'Finlandés'),
                 (250, 'FR', 'FRA', 'Francia', 'Francés'),
                 (276, 'DE', 'DEU', 'Alemania', 'Alemán'),
                 (300, 'GR', 'GRC', 'Grecia', 'Griego'),
                 (320, 'GT', 'GTM', 'Guatemala', 'Guatemalteco'),
                 (324, 'GN', 'GIN', 'Guinea', 'Guineano'),
                 (328, 'GY', 'GUY', 'Guyana', 'Guyanés'),
                 (332, 'HT', 'HTI', 'Haití', 'Haitiano'),
                 (340, 'HN', 'HND', 'Honduras', 'Hondureño'),
                 (348, 'HU', 'HUN', 'Hungría', 'Húngaro'),
                 (352, 'IS', 'ISL', 'Islandia', 'Islandés'),
                 (356, 'IN', 'IND', 'India', 'Indio'),
                 (360, 'ID', 'IDN', 'Indonesia', 'Indonesio'),
                 (364, 'IR', 'IRN', 'Irán', 'Iraní'),
                 (368, 'IQ', 'IRQ', 'Irak', 'Iraquí'),
                 (372, 'IE', 'IRL', 'Irlanda', 'Irlandés'),
                 (376, 'IL', 'ISR', 'Israel', 'Israelí'),
                 (380, 'IT', 'ITA', 'Italia', 'Italiano'),
                 (384, 'CI', 'CIV', 'Costa de Marfil', 'Marfileño'),
                 (388, 'JM', 'JAM', 'Jamaica', 'Jamaiquino'),
                 (392, 'JP', 'JPN', 'Japón', 'Japonés'),
                 (398, 'KZ', 'KAZ', 'Kazajistán', 'Kazajo'),
                 (400, 'JO', 'JOR', 'Jordania', 'Jordano'),
                 (404, 'KE', 'KEN', 'Kenia', 'Keniata'),
                 (408, 'KP', 'PRK', 'Corea del Norte', 'Norcoreano'),
                 (410, 'KR', 'KOR', 'Corea del Sur', 'Surcoreano'),
                 (414, 'KW', 'KWT', 'Kuwait', 'Kuwaití'),
                 (417, 'KG', 'KGZ', 'Kirguistán', 'Kirguís'),
                 (418, 'LA', 'LAO', 'Laos', 'Laosiano'),
                 (422, 'LB', 'LBN', 'Líbano', 'Libanés'),
                 (426, 'LS', 'LSO', 'Lesoto', 'Lesotense'),
                 (428, 'LV', 'LVA', 'Letonia', 'Letón'),
                 (430, 'LR', 'LBR', 'Liberia', 'Liberiano'),
                 (434, 'LY', 'LBY', 'Libia', 'Libio'),
                 (438, 'LI', 'LIE', 'Liechtenstein', 'Liechtensteiniano'),
                 (440, 'LT', 'LTU', 'Lituania', 'Lituano'),
                 (442, 'LU', 'LUX', 'Luxemburgo', 'Luxemburgués'),
                 (450, 'MG', 'MDG', 'Madagascar', 'Malgache'),
                 (454, 'MW', 'MWI', 'Malaui', 'Malauí'),
                 (458, 'MY', 'MYS', 'Malasia', 'Malasio'),
                 (462, 'MV', 'MDV', 'Maldivas', 'Maldivo'),
                 (466, 'ML', 'MLI', 'Malí', 'Maliense'),
                 (470, 'MT', 'MLT', 'Malta', 'Maltés'),
                 (478, 'MR', 'MRT', 'Mauritania', 'Mauritano'),
                 (480, 'MU', 'MUS', 'Mauricio', 'Mauriciano'),
                 (484, 'MX', 'MEX', 'México', 'Mexicano'),
                 (492, 'MC', 'MCO', 'Mónaco', 'Monegasco'),
                 (496, 'MN', 'MNG', 'Mongolia', 'Mongol'),
                 (498, 'MD', 'MDA', 'Moldavia', 'Moldavo'),
                 (499, 'ME', 'MNE', 'Montenegro', 'Montenegrino'),
                 (504, 'MA', 'MAR', 'Marruecos', 'Marroquí'),
                 (508, 'MZ', 'MOZ', 'Mozambique', 'Mozambiqueño'),
                 (512, 'OM', 'OMN', 'Omán', 'Omaní'),
                 (516, 'NA', 'NAM', 'Namibia', 'Namibio'),
                 (520, 'NR', 'NRU', 'Nauru', 'Nauruano'),
                 (524, 'NP', 'NPL', 'Nepal', 'Nepalí'),
                 (528, 'NL', 'NLD', 'Países Bajos', 'Neerlandés'),
                 (554, 'NZ', 'NZL', 'Nueva Zelanda', 'Neozelandés'),
                 (558, 'NI', 'NIC', 'Nicaragua', 'Nicaragüense'),
                 (562, 'NE', 'NER', 'Níger', 'Nigerino'),
                 (566, 'NG', 'NGA', 'Nigeria', 'Nigeriano'),
                 (578, 'NO', 'NOR', 'Noruega', 'Noruego'),
                 (586, 'PK', 'PAK', 'Pakistán', 'Pakistaní'),
                 (591, 'PA', 'PAN', 'Panamá', 'Panameño'),
                 (598, 'PG', 'PNG', 'Papúa Nueva Guinea', 'Papú'),
                 (600, 'PY', 'PRY', 'Paraguay', 'Paraguayo'),
                 (604, 'PE', 'PER', 'Perú', 'Peruano'),
                 (608, 'PH', 'PHL', 'Filipinas', 'Filipino'),
                 (616, 'PL', 'POL', 'Polonia', 'Polaco'),
                 (620, 'PT', 'PRT', 'Portugal', 'Portugués'),
                 (624, 'GW', 'GNB', 'Guinea-Bisáu', 'Guineano'),
                 (626, 'TL', 'TLS', 'Timor Oriental', 'Timorense'),
                 (630, 'PR', 'PRI', 'Puerto Rico', 'Puertorriqueño'),
                 (634, 'QA', 'QAT', 'Catar', 'Catarí'),
                 (642, 'RO', 'ROU', 'Rumanía', 'Rumano'),
                 (643, 'RU', 'RUS', 'Rusia', 'Ruso'),
                 (646, 'RW', 'RWA', 'Ruanda', 'Ruandés'),
                 (659, 'KN', 'KNA', 'San Cristóbal y Nieves', 'Cristobaleño'),
                 (662, 'LC', 'LCA', 'Santa Lucía', 'Santalucense'),
                 (670, 'VC', 'VCT', 'San Vicente y las Granadinas', 'Vincentino'),
                 (682, 'SA', 'SAU', 'Arabia Saudita', 'Saudí'),
                 (686, 'SN', 'SEN', 'Senegal', 'Senegalés'),
                 (688, 'RS', 'SRB', 'Serbia', 'Serbio'),
                 (694, 'SL', 'SLE', 'Sierra Leona', 'Sierraleonés'),
                 (702, 'SG', 'SGP', 'Singapur', 'Singapurense'),
                 (703, 'SK', 'SVK', 'Eslovaquia', 'Eslovaco'),
                 (704, 'VN', 'VNM', 'Vietnam', 'Vietnamita'),
                 (705, 'SI', 'SVN', 'Eslovenia', 'Esloveno'),
                 (706, 'SO', 'SOM', 'Somalia', 'Somalí'),
                 (710, 'ZA', 'ZAF', 'Sudáfrica', 'Sudafricano'),
                 (716, 'ZW', 'ZWE', 'Zimbabue', 'Zimbabuense'),
                 (724, 'ES', 'ESP', 'España', 'Español'),
                 (740, 'SR', 'SUR', 'Surinam', 'Surinamés'),
                 (748, 'SZ', 'SWZ', 'Suazilandia', 'Suazi'),
                 (752, 'SE', 'SWE', 'Suecia', 'Sueco'),
                 (756, 'CH', 'CHE', 'Suiza', 'Suizo'),
                 (760, 'SY', 'SYR', 'Siria', 'Sirio'),
                 (762, 'TJ', 'TJK', 'Tayikistán', 'Tayiko'),
                 (764, 'TH', 'THA', 'Tailandia', 'Tailandés'),
                 (768, 'TG', 'TGO', 'Togo', 'Togolés'),
                 (776, 'TO', 'TON', 'Tonga', 'Tongano'),
                 (780, 'TT', 'TTO', 'Trinidad y Tobago', 'Trinitense'),
                 (784, 'AE', 'ARE', 'Emiratos Árabes Unidos', 'Emiratí'),
                 (788, 'TN', 'TUN', 'Túnez', 'Tunecino'),
                 (792, 'TR', 'TUR', 'Turquía', 'Turco'),
                 (795, 'TM', 'TKM', 'Turkmenistán', 'Turcomano'),
                 (798, 'TV', 'TUV', 'Tuvalu', 'Tuvaluano'),
                 (800, 'UG', 'UGA', 'Uganda', 'Ugandés'),
                 (804, 'UA', 'UKR', 'Ucrania', 'Ucraniano'),
                 (807, 'MK', 'MKD', 'Macedonia del Norte', 'Macedonio'),
                 (818, 'EG', 'EGY', 'Egipto', 'Egipcio'),
                 (826, 'GB', 'GBR', 'Reino Unido', 'Británico'),
                 (834, 'TZ', 'TZA', 'Tanzania', 'Tanzano'),
                 (840, 'US', 'USA', 'Estados Unidos', 'Estadounidense'),
                 (858, 'UY', 'URY', 'Uruguay', 'Uruguayo'),
                 (860, 'UZ', 'UZB', 'Uzbekistán', 'Uzbeko'),
                 (862, 'VE', 'VEN', 'Venezuela', 'Venezolano'),
                 (887, 'YE', 'YEM', 'Yemen', 'Yemení'),
                 (894, 'ZM', 'ZMB', 'Zambia', 'Zambiano');