INSERT INTO estado_matricula(id, descripcion, detalle, codigo_sistema) VALUES
       (1,'PREINSCRIPCION','INTENCIÓN DE MATRICULARSE', 'PREINSCRIPCION'),
       (2, 'PENDIENTE','FALTA ALGUN REQUISITO', 'PENDIENTE'),
       (3, 'ACTIVA','MATRICULA VIGENTE', 'ACTIVA'),
       (4, 'SUSPENDIDA','PAUSE TEMPORAL', 'SUSPENDIDA'),
       (5, 'ANULADA','ANTES DE INICIAR, PARA ELIMINAR', 'ANULADA'),
       (6, 'RETIRADA','SE RETIRA POR ALGUN MOTIVO', 'RETIRADA'),
       (7, 'TRASLADADA','SE TRASLADA A OTRA INSTITUCION', 'TRASLADADA');